version: 1
schedule:
  type: "simple"
  interval: "5s"
max-failures: 10
workflow:
  collect:
    metrics:
      /intel/iostat/avg-cpu/*: {}
    publish:
      - plugin_name: "file"
        config:
          file: "/tmp/cpu_stat.log"
