---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow: 
    collect:
      metrics:
        /intel/procfs/cpu/*/active_jiffies: {}						 
        /intel/procfs/cpu/*/active_percentage: {}
        /intel/procfs/cpu/*/guest_jiffies: {}
        /intel/procfs/cpu/*/guest_nice_jiffies: {}
        /intel/procfs/cpu/*/guest_nice_percentage: {}
        /intel/procfs/cpu/*/guest_percentage: {}
        /intel/procfs/cpu/*/idle_jiffies: {}
        /intel/procfs/cpu/*/idle_percentage: {}		
        /intel/procfs/cpu/*/iowait_jiffies: {}
        /intel/procfs/cpu/*/iowait_percentage: {}				
        /intel/procfs/cpu/*/system_jiffies: {}
        /intel/procfs/cpu/*/system_percentage: {}	
        /intel/procfs/cpu/*/user_jiffies: {}	
        /intel/procfs/cpu/*/user_percentage: {}
        /intel/procfs/cpu/*/utilization_jiffies: {}
        /intel/procfs/cpu/*/utilization_percentage: {}
      publish:
        -
          plugin_name: "influxdb"
          config:
            host: "influxdb"
            port: 8086
            database: "k8s"
            user: "admin"
            password: "admin"
    