version: '2'
services:
  main:
    image: candysmurfhub/snap-es-mon-docker:latest
    container_name: snap-elasticsearch-monitor
    environment:
      SNAP_VERSION: 0.16.1
      FILE_PUB_PLUGIN_VER: 2
      ELASTICSEARCH_COL_PLUGIN_VER: 3
      INFLUXDB_PUB_PLUGIN_VER: 15
    depends_on:
      - snap-elasticsearch
      - es-node
      - influxdb
      - grafana
  influxdb:
    container_name: influxdb
    image: tutum/influxdb:0.9
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8083" 
      - "8086"
    environment:
      - PRE_CREATE_DB=k8s
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    expose:
      - "3000" 
    depends_on:
      - influxdb
  snap-elasticsearch:
    image: elasticsearch:2.4.4
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports: 
      - "9200:9200"
  es-node:
    image: elasticsearch:2.4.4
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    depends_on:
      - snap-elasticsearch
