#!/bin/sh

set -e
set -u
set -o pipefail


/opt/snap/bin/snaptel task create -t /opt/snap/tasks/example-influxdb-task.yml
/opt/snap/bin/snaptel task create -t /opt/snap/tasks/example-psutil-task.yml
/opt/snap/bin/snaptel task create -t /opt/snap/tasks/example-cpu-task.yml
/opt/snap/bin/snaptel task create -t /opt/snap/tasks/example-disk-task.yml
/opt/snap/bin/snaptel task create -t /opt/snap/tasks/example-mem-task.yml